# Generated by Django 4.2.11 on 2024-06-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deshboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_course_data_header_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '2. Create Course Detials Title',
                'verbose_name_plural': '2. Create Course Detials Title',
            },
        ),
        migrations.CreateModel(
            name='Module_Name_Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Module_number_and_Title', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '6. Set Week Wise Module ',
                'verbose_name_plural': '6. Set Week Wise Module ',
            },
        ),
        migrations.CreateModel(
            name='Teacher_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Teacher_name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Teacher_position', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('Teacher_About_text', models.TextField()),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '10. Course Teacher About',
                'verbose_name_plural': '10. Course Teacher About',
            },
        ),
        migrations.CreateModel(
            name='Student_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Title_Name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Question_Answer_Text', models.TextField()),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': ' 11. Student Course Related Question And Answer',
                'verbose_name_plural': ' 11. Student Course Related Question And Answer',
            },
        ),
        migrations.CreateModel(
            name='Student_openion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Student_name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('Openion_text', models.TextField()),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '9. Student openion',
                'verbose_name_plural': '9. Student openion',
            },
        ),
        migrations.CreateModel(
            name='Puropse_of_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('Purpose_Text', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '4. Puropse of course Deta Set',
                'verbose_name_plural': '4. Puropse of course Deta Set',
            },
        ),
        migrations.CreateModel(
            name='Project_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '8. Project Image',
                'verbose_name_plural': '8. Project Image',
            },
        ),
        migrations.CreateModel(
            name='Module_Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Week_name', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': ' 5. Set Module Week',
                'verbose_name_plural': ' 5. Set Module Week',
            },
        ),
        migrations.CreateModel(
            name='Module_Video_And_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Title', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('video', models.FileField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/video/')),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
                ('select_Module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.module_name_number')),
                ('select_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.module_week')),
            ],
            options={
                'verbose_name': '7. Set Module Wise video ',
                'verbose_name_plural': '7. Set Module Wise video ',
            },
        ),
        migrations.AddField(
            model_name='module_name_number',
            name='select_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.module_week'),
        ),
        migrations.CreateModel(
            name='Learning_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Learning_Topics', models.CharField(blank=True, default=' ', max_length=200, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '12. EveryThing in this course',
                'verbose_name_plural': '12. EveryThing in this course',
            },
        ),
        migrations.CreateModel(
            name='Course_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_about_text', models.TextField(blank=True, null=True)),
                ('course_image', models.ImageField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/')),
                ('video', models.FileField(blank=True, default=' ', null=True, upload_to='Home_Page_Two/media/video')),
                ('chooes_Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
            ],
            options={
                'verbose_name': '1. Course Header About',
                'verbose_name_plural': '1. Course Header About',
            },
        ),
        migrations.CreateModel(
            name='Course_All_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Left_text', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('Right_text', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('chooes_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
                ('choose_Header_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Home_Page_Two.all_course_data_header_name')),
            ],
            options={
                'verbose_name': '3. Title Wise Show Data',
                'verbose_name_plural': '3. Title Wise Show Data',
            },
        ),
    ]
