# Generated by Django 4.2.11 on 2024-06-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Deshboard', '0001_initial'),
        ('Login_Logout', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deshboard.all_category_card_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_teacher_batch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Create Batch',
                'verbose_name_plural': 'Create Batch',
            },
        ),
        migrations.CreateModel(
            name='Meet_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnig_topic_name', models.CharField(max_length=500)),
                ('meetLink', models.URLField(max_length=400)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
            ],
            options={
                'verbose_name': 'Meet Link',
                'verbose_name_plural': 'Meet Link',
            },
        ),
        migrations.CreateModel(
            name='Batch_wise_Student_Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_User_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Student_profile_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_id', to='Login_Logout.profile')),
                ('Student_profile_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login_Logout.profile')),
                ('batch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
            ],
        ),
        migrations.CreateModel(
            name='batch_wise_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
            ],
            options={
                'verbose_name': 'Batch Wise Message',
                'verbose_name_plural': 'Batch Wise Message',
            },
        ),
        migrations.CreateModel(
            name='Batch_wise_Assingment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assingment_topic_name', models.CharField(max_length=150)),
                ('Assingment_pdf', models.FileField(blank=True, default=' ', null=True, upload_to='Custom_Admin_panel/media/')),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
            ],
            options={
                'verbose_name': 'Batch Wise Assingment',
                'verbose_name_plural': 'Batch Wise Assingment',
            },
        ),
        migrations.CreateModel(
            name='Batch_time_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_Time', models.CharField(blank=True, max_length=50, null=True)),
                ('end_Time', models.CharField(blank=True, max_length=50, null=True)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
            ],
            options={
                'verbose_name': 'Batch Time Set',
                'verbose_name_plural': 'Batch Time Set',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendence',
                'verbose_name_plural': 'Attendence',
            },
        ),
        migrations.CreateModel(
            name='Assingment_Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assingment_pdf', models.FileField(blank=True, default=' ', null=True, upload_to='Custom_Admin_panel/media/')),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
            ],
            options={
                'verbose_name': 'Assingment Submit',
                'verbose_name_plural': 'Assingment Submit',
            },
        ),
        migrations.CreateModel(
            name='Assingment_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_pdf', models.FileField(blank=True, default=' ', null=True, upload_to='Custom_Admin_panel/media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assingment Result',
                'verbose_name_plural': 'Assingment Result',
            },
        ),
    ]
