# Generated by Django 4.2.11 on 2024-06-19 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Custom_Admin_panel', '0002_remove_attendence_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('batchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.create_batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendence system',
                'verbose_name_plural': 'Attendence system',
            },
        ),
    ]
