# Generated by Django 4.2.11 on 2024-06-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Custom_Admin_panel', '0004_meet_link_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet_link',
            name='attend',
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.BooleanField(default=False)),
                ('meet_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Custom_Admin_panel.meet_link')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
