# Generated by Django 4.2.11 on 2024-06-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_Admin_panel', '0005_remove_meet_link_attend_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence_system',
            name='batchId',
        ),
        migrations.RemoveField(
            model_name='attendence_system',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='student_attendance',
            options={'verbose_name': 'Student Attendence', 'verbose_name_plural': 'Student Attendence'},
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Attendence_system',
        ),
    ]
