# Generated by Django 4.2.11 on 2024-06-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneUs_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_seen', models.BooleanField(default=False)),
            ],
        ),
    ]
