# Generated by Django 4.2.11 on 2024-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media', '0002_phoneus_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneus_form',
            name='course_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
