# Generated by Django 4.2.11 on 2024-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social_Media', '0003_phoneus_form_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneus_form',
            name='message',
        ),
    ]
