# Generated by Django 4.2.11 on 2024-06-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, default='socialmedia/pro.png', null=True, upload_to='Student_Profile/media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentImage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student image',
                'verbose_name_plural': 'Student image',
            },
        ),
        migrations.CreateModel(
            name='Student_Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Certificate', models.FileField(blank=True, default=' ', null=True, upload_to='Student_Profile/media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Certificate',
                'verbose_name_plural': 'Student Certificate',
            },
        ),
    ]
